# ???? ?????????? ??? (?? ????????? ??), ??????????? ? ????????? ?? study_db. 
# ?? Railway ??????????? ??????? ??????.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/study_db?createDatabaseIfNotExist=true}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:ozntKhKuxPFMtqKGkTCispjKXoFTclBv}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}