spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# ??????????: ???????? ??????? ??? ?????????? ?????? ? MySQL 8+ ?? Railway
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ???? ????? ??????????? ????????????? ??????????
server.port=${PORT:8080}